ShopBay/Controllers/SignInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopBay.Models;
using System.Web.Security;

namespace ShopBay.Controllers
{
    public class SignInController : Controller
    {

        ShopBayEntities1 bd = new ShopBayEntities1();
        // GET: SignIn
        public ActionResult SignIn()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ValidarLogin(Users usuario)
        {
            if(usuario.Username.Equals("Steven") || usuario.Username.Equals("Andres") || usuario.Username.Equals("Jonathan"))
            {
                if (usuario.Username.Equals(usuario.Password))
                {
                    Session["isAdmin"] = "yes";
                    Session["AdminName"] = usuario.Username;
                    return RedirectToAction("Admin", "Admin");
                }else
                {
                    return View();
                }
            }else
            {
                var user = bd.Users.ToList();
                foreach (var item in user)
                {
                    if (item.Username == usuario.Username)
                    {
                        if (item.Password.Equals(usuario.Password))
                        {
                            FormsAuthentication.SetAuthCookie(usuario.Username, true);
                            Session["UserID"] = item.UserID;
                            Session["Username"] = item.Username;
                            Session["Type"] = item.Type;
                            Session["Telephone"] = item.Telephone;
                            Session["Rate"] = item.Rate;
                            Session["Mail"] = item.Mail;
                            Session["Information"] = item.Information;
                            Session["AccMoney"] = item.AccMoney;
                            Session["Image"] = item.Image;
                            return RedirectToAction("Index", "Home");
                        }
                    }
                    ModelState.AddModelError("", "Wrong username or password");
                }
            }
            return View();    
        }

        public ActionResult SalirAdmin()
        {
            Session["isAdmin"] = null;
            Session["AdminName"] = null;
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Salir()
        {
            FormsAuthentication.SignOut();
            var movementsOfUser = bd.Movements.SqlQuery("SELECT * FROM Movements WHERE UserID = " + Session["UserID"]);
            int currentCash = 0;
            foreach (var movement in movementsOfUser)
            {
                currentCash = currentCash + Convert.ToInt32(movement.Ammount);
            }
            bd.Users.Find(Session["UserID"]).AccMoney = currentCash;
            bd.SaveChanges();
            Session["UserID"] = null;
            Session["Username"] = null;
            Session["Type"] = null;
            Session["Telephone"] = null;
            Session["Rate"] = null;
            Session["Mail"] = null;
            Session["Information"] = null;
            Session["AccMoney"] = null;
            Session["Image"] = null;
            return RedirectToAction("Index", "Home");
        }


    }
}

ShopBay/Views/SignIn/SignIn.cshtml
@using ShopBay.Models
@model Users
@{
    ViewBag.Title = "Log In";
}

<div class="row pt-4">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("ValidarLogin", "SignIn", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <h4 class="lead">Log In with your ShopBay account.</h4>
                <hr />
                @Html.AntiForgeryToken()
                <label>Username</label>
                <div class="form-group">
                    @Html.TextBoxFor(m => m.Username, new { @class = "form-control col-lg-7" })
                    @Html.ValidationMessageFor(m => m.Username, "", new { @class = "text-danger" })
                </div>
                <label>Password</label>
                <div class="form-group">
                    @Html.PasswordFor(m => m.Password, new { @class = "form-control col-lg-7" })
                    @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                </div>
                <div class="form-group pl-0">
                    <div class="pl-0">
                        <input type="submit" value="Log In" class="btn btn-primary my-2" />
                    </div>
                </div>
                <p>
                    Do not have an account?@Html.ActionLink(" Join us!", "Register", "Account")
                </p>
            }
        </section>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}